name: Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted, media]

    steps:
    - uses: actions/checkout@v3
    - name: Build and run the Docker image
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        BOT_CLIENT_ID: ${{ secrets.BOT_CLIENT_ID }}
      run: docker compose up --build -d --no-deps --force-recreate